version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    volumes:
      - "./api/:/app"
    restart: unless-stopped
  frontend:
    build: wiki
    ports:
      - "8080:80"
    volumes:
      - "./wiki/build/wiki:/var/www/html"
    restart: unless-stopped
