version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    volumes:
      - "./api/:/app"
    restart: unless-stopped
    frontend:
      build: wiki
      ports:
        - "4200:4200"
      volumes:
        - "./wiki/build/wiki:/app"
      restart: unless-stopped
