- name: FooterRoute
  description: A Rest endpoint /api/footer giving diverse information about the footer of a webpage
  sections:
    - type: 10
      title: Method signature
      payload: |-
        export function FooterDescription(app: any);
      css: language-ts
    - type: 0
      title: parameters
      payload: |-
        FooterDescription takes an app as input.
        This app is of the type ExpressApplication as declared by the express framework
    - type: 2
      title: Routes
    - type: 10
      title: info
      payload: |-
        /api/footer
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns json containing the entire footer.
    - type: 10
      title: info
      payload: |-
        {
          sections: [
            {
              name: "Links",
              description: "Important link",
              links: [
                {
                  name: "Github",
                  logo: "fab fa-github",
                  url: "https://github.com/F0xedb/WikiTS"
                }
              ]
            }
          ]
        }
      css: language-json
    - type: 10
      title: declaration
      payload: |-
        /api/footer/:id
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns a specific footer section.
    - type: 10
      title: info
      payload: |-
        {
          name: "Links",
          description: "Important link",
          links: [
            {
              name: "Github",
              logo: "fab fa-github",
              url: "https://github.com/F0xedb/WikiTS"
            }
          ]
        }
      css: language-json
