
# MIT License
# 
# Copyright (c) 2020 Meyers Tom
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
- name: FooterRoute
  description: A Rest endpoint /api/footer giving diverse information about the footer of a webpage
  sections:
    - type: 10
      title: Method signature
      payload: |-
        export function FooterDescription(app: any);
      css: language-ts
    - type: 0
      title: parameters
      payload: |-
        FooterDescription takes an app as input.
        This app is of the type ExpressApplication as declared by the express framework
    - type: 2
      title: Routes
    - type: 10
      title: info
      payload: |-
        /api/footer
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns json containing the entire footer.
    - type: 10
      title: info
      payload: |-
        {
          sections: [
            {
              name: "Links",
              description: "Important link",
              links: [
                {
                  name: "Github",
                  logo: "fab fa-github",
                  url: "https://github.com/F0xedb/WikiTS"
                }
              ]
            }
          ]
        }
      css: language-json
    - type: 10
      title: declaration
      payload: |-
        /api/footer/:id
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns a specific footer section.
    - type: 10
      title: info
      payload: |-
        {
          name: "Links",
          description: "Important link",
          links: [
            {
              name: "Github",
              logo: "fab fa-github",
              url: "https://github.com/F0xedb/WikiTS"
            }
          ]
        }
      css: language-json
