- name: GeneralRoute
  description: A Rest endpoint /api/general giving diverse information the general state of the wiki
  sections:
    - type: 10
      title: Method signature
      payload: |-
        export function GeneralDescription(app: any);
      css: language-ts
    - type: 0
      title: parameters
      payload: |-
        GeneralDescription takes an app as input.
        This app is of the type ExpressApplication as declared by the express framework
    - type: 2
      title: Routes
    - type: 10
      title: info
      payload: |-
        /api/general
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns json containing general website information.
    - type: 10
      title: info
      payload: |-
        {
          name: "WikiTS",
          logo: "a link or encoded data such as base64",
          description: "WikiTS example response",
          company: "Company Name"
        }
      css: language-json
