- name: NavigationRoute
  description: A Rest endpoint /api/nav giving diverse information about the navigation around the wiki
  sections:
    - type: 1
      title: Some title
      payload: This page is used as a reference in the main page
    - type: 9
      title: We even have links as a section
      payload: https://tos.odex.be
    - type: 9
      title: Or with alternate text
      payload: link here;https://tos.odex.be
