
# MIT License
# 
# Copyright (c) 2020 Meyers Tom
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
- name: NavigationRoute
  description: A Rest endpoint /api/nav giving diverse information about the navigation around the wiki
  sections:
    - type: 10
      title: Method signature
      payload: |-
        export function NavigationDescription(app: any);
      css: language-ts
    - type: 0
      title: parameters
      payload: |-
        NavigationDescription takes an app as input.
        This app is of the type ExpressApplication as declared by the express framework
    - type: 2
      title: Routes
    - type: 10
      title: info
      payload: |-
        /api/nav
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns a navigation object as defined in the DeclarationDefinition
    - type: 10
      title: info
      payload: |-
        {
          name: "WikiTS Navigation",
          sections: [
            {
              name: "Classes",
              elements: [
                {
                  name: "Class1",
                  pageID: 1
                },
                {
                  name: "Class2",
                  pageID: 2
                },
              ]
            }
          ]
        }
      css: language-json
    - type: 10
      title: declaration
      payload: |-
        /api/nav/:id
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns a navigation section.
    - type: 10
      title: info
      payload: |-
        {
          name: "Classes",
          elements: [
            {
              name: "Class1",
              pageID: 1
            },
            {
              name: "Class2",
              pageID: 2
            },
          ]
        }
      css: language-json
    - type: 10
      title: declaration
      payload: |-
        /api/nav/:id/:elementID
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns a navigation element from a specific section.
    - type: 10
      title: info
      payload: |-
        {
          name: "Class1",
          pageID: 1
        }
      css: language-json
    - type: 5
      title: pageID
      payload: pageID is a reference to the array index of the pages section in the declaration file
