- name: SectionRoutes
  description: A Rest endpoint /api/section giving diverse information about a specific section of a wiki page
  sections:
    - type: 10
      title: Method signature
      payload: |-
        export function SectionDescription(app: any);
      css: language-ts
    - type: 0
      title: parameters
      payload: |-
        SectionDescription takes an app as input.
        This app is of the type ExpressApplication as declared by the express framework
    - type: 2
      title: Routes
    - type: 10
      title: info
      payload: |-
        /api/section/;pageID/:sectionID
      css: language-sh
    - type: 0
      title: Action
      payload: |-
        Returns json containing an entire section .
    - type: 10
      title: info
      payload: |-
        {
          type: 10,
          title: "Some title",
          inheritsID: 1,
          payload: "echo hello",
          width: "300px",
          height: "300px",
          css: "language-sh"
        },
      css: language-json
    - type: 5
      title: sections
      payload: A section does not have to contain all data. The width and height property is used for images, css is the prismjs selector to indicate the language on syntax highlighting, inheritsID is used in case you want to tell this section inherits a certain page in the wiki as defined by the pageID
