- name: SectionRoutes
  description: A Rest endpoint /api/section giving diverse information about a specific section of a wiki page
  sections:
    - type: 1
      title: Some title
      payload: This page is used as a reference in the main page
    - type: 9
      title: We even have links as a section
      payload: https://tos.odex.be
    - type: 9
      title: Or with alternate text
      payload: link here;https://tos.odex.be
